version: '2'

services:

  # A simple backend servers written in Golang that returns passwords in
  # plaintext.  What could possibly go wrong?
  server1:
    build: .
    ports:
    - 8501:8501

  # Captures packet data from the network and deocdes it as HTTP.  Prints
  # HTTP response bodies.
  tshark:
    image: opennsm/tshark
    cap_add:
    - NET_RAW
    - NET_ADMIN
    network_mode: "host"
    command: [ "tshark", "-qi", "any", "-O", "http", "-f", "tcp port 4141", "-Y", "http.response.code == 200", "-T", "fields", "-e", "text" ]

  # Slow Cooker load generator.  Configured to send a total of 300 requests per
  # second to the backend server.
  slow_cooker:
    image: buoyantio/slow_cooker:1.1.0-golang1.8rc2
    entrypoint: /bin/sh
    command: >
      -c 'sleep 15 && slow_cooker -noreuse -metric-addr :8505 -qps 20 -concurrency 15 -interval 5s -totalRequests 10000000 http://linkerd:4140'

  linkerd-client:
    image: buoyantio/linkerd:1.3.5
    ports:
      - 4140:4140
      - 9990:9990
    volumes:
      - ./linkerd-client.yml:/io/buoyant/linkerd/config.yml:ro
      - ./disco:/disco
      - ./ca-chain.cert.pem:/ca-chain.cert.pem
    command:
      - "/io/buoyant/linkerd/config.yml"

  linkerd-server:
    image: buoyantio/linkerd:1.3.5
    ports:
      - 4141:4141
      - 9991:9991
    volumes:
      - ./linkerd-server.yml:/io/buoyant/linkerd/config.yml:ro
      - ./disco:/disco
      - ./cert.pem:/cert.pem
      - ./private.pk8:/private.pk8
    command:
      - "/io/buoyant/linkerd/config.yml"
